"""add skills and github_url to profiles

Revision ID: 0b663a96b349
Revises: 005a7387fadb
Create Date: 2026-09-03 16:08:30.923904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b663a96b349'
down_revision = '005a7387fadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('RejectionReason')
        batch_op.drop_column('Duration')
        batch_op.drop_column('Hashtags')
        batch_op.drop_column('ThumbnailURL')
        batch_op.drop_column('ViewsCount')
        batch_op.drop_column('Summary')
        batch_op.drop_column('LikesCount')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('GithubURL', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('GithubURL')
        batch_op.drop_column('Skills')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LikesCount', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('Summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ViewsCount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ThumbnailURL', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Hashtags', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Duration', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('RejectionReason', sa.TEXT(), nullable=True))

    op.create_table('likes',
    sa.Column('LikeID', sa.INTEGER(), nullable=False),
    sa.Column('UserID', sa.INTEGER(), nullable=False),
    sa.Column('ContentID', sa.INTEGER(), nullable=False),
    sa.Column('CreatedAt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ContentID'], ['content.ContentID'], name=op.f('fk_likes_ContentID_content')),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], name=op.f('fk_likes_UserID_users')),
    sa.PrimaryKeyConstraint('LikeID'),
    sa.UniqueConstraint('UserID', 'ContentID', name=op.f('unique_user_content_like'))
    )
    # ### end Alembic commands ###
